//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_branch
    {
        public int ID { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string Phone1 { get; set; }
        public string Fax { get; set; }
        public string web { get; set; }
        public string BankStatus { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public string AccountNo { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string ADDR3 { get; set; }
        public string PHONE2 { get; set; }
        public string Gl_Code { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> ServerID { get; set; }
        public Nullable<int> LocalUploadFlag { get; set; }
        public string BankType { get; set; }
    }
}
