//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_info
    {
        public int ID { get; set; }
        public string BankName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string BankType { get; set; }
    }
}
