//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerInfo
    {
        public FarmerInfo()
        {
            this.ItemPurchaseMsts = new HashSet<ItemPurchaseMst>();
        }
    
        public int ID { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> DistricID { get; set; }
        public Nullable<int> ThanaID { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PostalCode { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Code { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual COUNTRY_INFO COUNTRY_INFO { get; set; }
        public virtual DISTRICTINFO DISTRICTINFO { get; set; }
        public virtual THANAINFO THANAINFO { get; set; }
        public virtual ICollection<ItemPurchaseMst> ItemPurchaseMsts { get; set; }
    }
}
