//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemWithUOM
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BranchName { get; set; }
        public int UOMID { get; set; }
        public string UOMName { get; set; }
        public int DiscountAmount { get; set; }
        public int Discount { get; set; }
        public Nullable<decimal> UnitsInStock { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string StyleNo { get; set; }
        public string Design { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string ItemCode { get; set; }
    }
}
