//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInfo
    {
        public ItemInfo()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubcategoryID { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int UOMID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> ClosingStock { get; set; }
        public Nullable<decimal> ClosingAmount { get; set; }
        public string StyleNo { get; set; }
        public string Design { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
