//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfoForMoneyReceipt
    {
        public long OrderDetailID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string Design { get; set; }
        public string Session { get; set; }
        public string FabricPattan { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string TaxCategoryID { get; set; }
        public Nullable<decimal> vatRate { get; set; }
        public Nullable<decimal> CashReceived { get; set; }
        public Nullable<decimal> CashRefund { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemSize { get; set; }
        public string M_Code { get; set; }
        public string UOMName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public decimal ChangeQty { get; set; }
        public decimal ReturnQuantity { get; set; }
        public Nullable<decimal> ItemDiscountAmount { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string ContactName { get; set; }
        public string UserName { get; set; }
        public string ServiceBy { get; set; }
        public string FullName { get; set; }
        public string PaymentMode { get; set; }
        public string Type { get; set; }
        public string ItemType { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
    }
}
