//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPaymentMst
    {
        public SalaryPaymentMst()
        {
            this.SalaryPaymentDtls = new HashSet<SalaryPaymentDtl>();
        }
    
        public int ID { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public Nullable<System.DateTime> SalaryPayDate { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual ICollection<SalaryPaymentDtl> SalaryPaymentDtls { get; set; }
    }
}
