//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANAINFO
    {
        public THANAINFO()
        {
            this.FarmerInfoes = new HashSet<FarmerInfo>();
        }
    
        public string THANA_CODE { get; set; }
        public string THANA_NAME { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<FarmerInfo> FarmerInfoes { get; set; }
    }
}
