//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTL_USERGRANT
    {
        public string USER_NAME { get; set; }
        public string USER_GRP { get; set; }
        public string MOD_ID { get; set; }
        public string ALLOW_ADD { get; set; }
        public string ALLOW_EDIT { get; set; }
        public string ALLOW_VIEW { get; set; }
        public string ALLOW_DELETE { get; set; }
        public string ALLOW_PRINT { get; set; }
        public string ALLOW_AUTHO { get; set; }
        public string DISPFLAG { get; set; }
    }
}
