//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ItemPurchaseHistoryorStatus
    {
        public int ID { get; set; }
        public string PoCode { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string ChallanNo { get; set; }
        public string FarmerName { get; set; }
        public string StatusType { get; set; }
        public string FarmerMobile { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ItemQuantity { get; set; }
        public string Satt { get; set; }
    }
}
