//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetItemPurchaseDetails
    {
        public long ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string PO { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public string AggentName { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo { get; set; }
        public string ItemCode { get; set; }
        public string BatchNo { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> ItemPurchaseMstID { get; set; }
    }
}
