//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICTINFO
    {
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string DIVISION_CODE { get; set; }
    }
}
