//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NationalID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Religion { get; set; }
        public string MaritalStatus { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string JobStatus { get; set; }
        public string Mobile { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] Image { get; set; }
    }
}
