//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMaster
    {
        public SalesMaster()
        {
            this.SalesDetails = new HashSet<SalesDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> CashReceived { get; set; }
        public Nullable<decimal> CashRefund { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<short> PaymentMethodID { get; set; }
        public string PaymentMethodNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<short> OrderStatusID { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<int> BankID { get; set; }
        public string CheckORCardNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> NewInvoiceID { get; set; }
    
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
    }
}
