//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public int ID { get; set; }
        public Nullable<long> MstID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ReturnQuantity { get; set; }
        public Nullable<int> UploadFlag { get; set; }
        public Nullable<int> ChangeQty { get; set; }
    
        public virtual SalesMaster SalesMaster { get; set; }
    }
}
